# Generated by Django 4.0.3 on 2022-03-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_departament'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='departament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.departament'),
        ),
    ]
